---
- name: vscode - add repo
  become: true
  yum_repository:
    name: code
    description: Visual Studio Code
    gpgcheck: yes
    enabled: yes
    file: vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    baseurl: https://packages.microsoft.com/yumrepos/vscode
- name: vscode - install
  become: true
  yum:
    name: code
    state: present
